name: AutoSchematic
version: '${project.version}'
main: ir.wylot.autoschematic.AutoSchematic
api-version: '1.20'
authors: [Soheil Talaee]
description: Load schematic on server load at a position to prevent block grief and keep spawn safe!
website: https://github.com/thewylot
depend:
  - WorldEdit
